config/routes.rb
Rails.application.routes.draw do
  get :sales, to: 'sales#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/good.rb
class Good < ApplicationRecord
  has_many :periods, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  def name=(value)
    write_attribute(:name, value.downcase) if value
  end
end

app/models/period.rb
class Period < ApplicationRecord
  scope :during_period_revenue_sum, -> (from, to) { where('date BETWEEN ? AND ?', Date.parse(from), Date.parse(to)).sum(:revenue) }

  belongs_to :good

  validates :date, presence: true, timeliness: { type: :date }
  validates :revenue, presence: true, numericality: true

  def revenue
    self[:revenue].to_f
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :check_date_params, only: :index

  def index
    respond_to do |format|
      if @errors.any?
        format.json { render json: { errors: @errors }, status: 422 }
      else
        @goods = Good.includes(:periods)
        format.json
      end

      format.html
      format.js
    end
  end

  private

  def check_date_params
    @errors = { }

    %i[from to].each do |attr|
      @errors[attr.to_sym] = "Неверный формат #{attr}" unless correct_format?(params[attr])
    end

    if @errors.empty?
      @errors[:from_to] = "From не может быть больше TO" if Date.parse(params[:from]) > Date.parse(params[:to])
    end
  end

  def correct_format?(date)
    begin
      Date.parse(date)
    rescue
      return false
    end
    true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoonyxTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sales/_error.html.erb
<% if @errors.any? %>
  <% @errors.each do |_, v| %>
    <p style="color: red"><strong></strong><%= v %></p>
  <% end %>
<% end  %>

app/views/sales/_good.html.erb
<tr>
  <td><%= good.name %></td>
  <td><%= good.periods.during_period_revenue_sum(params[:from], params[:to]) %></td>
</tr>

app/views/sales/index.html.erb
<div class="errors">
  <%= render partial: 'sales/error' %>
</div>

<div class="filter">
  <%= form_tag sales_path, method: :get, remote: true do %>
    <%= label_tag :from %>
    <%= text_field_tag :from, params[:from], placeholder: "Выберите дату ОТ" %>
    <br />
    <%= label_tag :to %>
    <%= text_field_tag :to, params[:to], placeholder: "Выберите дату ДО" %>
    <br />
    <%= submit_tag 'Обновить' %>
  <% end %>
</div>

<div class="table">
  <table border="1">
    <thead>
      <tr>
        <th>Название</th>
        <th>Сумма</th>
      </tr>
    </thead>
    <tbody>
      <% if @goods && @goods.any? %>
        <% @goods.each do |good| %>
          <%= render 'sales/good', good: good %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/sales/index.js.erb
document.getElementsByClassName('errors')[0].innerHTML = '';

<% if @errors.any? %>
  document.getElementsByClassName('errors')[0].innerHTML = "<%= j render partial: 'sales/error' %>"
<% end %>

document.getElementsByTagName('tbody')[0].innerHTML = "<%= j render partial: 'sales/good', collection: @goods, as: :good %>";